# the pool size(the number of client)  
#memcached:
#  connectionPoolSize: 50
#  failureMode: true
#  host: 127.0.0.1
#  port: 11211
#  weight: 1


# datasource
db:
  url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf8
  username: root
  password: root
  maxActive: 20
  initialSize: 1