server:
  port: 8888
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:9999/eureka/
  instance:
    hostname: p1
spring:
  application:
    name: eureka-server
